---
deployment:
  tasks:
    - export NVM_DIR="$HOME/.nvm"
    - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    - nvm use v20.17.0  # veya projene uygun sürüm
    - export PATH=$PATH:$NVM_DIR/versions/node/v20.17.0/bin
    - npm install
    - npm run build
    - export DEPLOYPATH=/home/httpdvfi/public_html/
    - /bin/cp -R dist/* $DEPLOYPATH